id = "paper-theme"
name = "Paper Theme"
version = "0.0.1"
schema_version = 1
authors = ["Declan"]
description = "A minimal, low-contrast theme for Zed."
repository = "https://github.com/Declan-22/paper-theme"
